# Generated by Django 5.2.1 on 2025-06-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_main_image_alter_subimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
