# Generated by Django 5.2.1 on 2025-06-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='conversation_conversation',
        ),
    ]
